Kafka:
  host: sb-uwf3:7078
  partition: 0
  topicToUse: ALEX
OAI:
  granularity: YYYY-MM-DDThh:mm:ssZ
  httpproxy: null
  metadataPrefix: marc21
  resumptionToken: null
  setName: null
  setSpec: Shib_OAI
  stoppageTime: '2017-07-09T13:10:32Z'
  timestampUTC: '2017-07-09T11:10:26Z'
  until: null
  url: https://eu.alma.exlibrisgroup.com/view/oai/41BIG_INST/request
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
