Kafka:
  host: localhost:9092
  partition: 1
  topicToUse: HEMU
OAI:
  granularity: YYYY-MM-DDThh:mm:ssZ
  httpproxy: null
  metadataPrefix: marcxml
  resumptionToken: null
  setName: null
  setSpec: SWISSBIB-FULL-HSB01
  stoppageTime: '2017-07-09T20:36:55Z'
  timestampUTC: '2017-07-09T18:36:43Z'
  until: null
  url: http://opacbiblio.hemu-cl.ch/cgi-bin/koha/oai.pl
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
