

OAI:
  metadataPrefix: marc21
  setName:
  resumptionToken:
  setSpec: SWISSBIB-FULL-HSB01
  stoppageTime: 2016-05-03 22:37:33.421592
  timestampUTC: 2016-08-01T00:31:18Z
  url: http://aleph.unisg.ch/cgi-bin/OAI
  httpproxy:
  from: 2016-09-11T00:00:42Z
  until: 2016-09-13T00:00:42Z

Processing:
  encodeUnicodeAsUTF8:
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>


Kafka:
  host: localhost:9092
  topicToUse: OAI1
  partition: 1

