Kafka:
  host: sb-uwf3:7078
  partition: 0
  topicToUse: RETROSEALS
OAI:
  granularity: YYYY-MM-DDThh:mm:ssZ
  httpproxy: null
  metadataPrefix: oai_dc
  resumptionToken: null
  setName: null
  setSpec:
  stoppageTime: '2017-07-09T13:10:32Z'
  timestampUTC: '2017-07-09T11:10:26Z'
  until: null
  url: http://www.e-periodica.ch/oai/dataprovider
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
