DB:
  dbname: nativeSources
  collection:
    name : sourceGruyter
    docfield: jatsRecord

HOST:
  authDB: admin
  password: null
  port: 29017
  server: localhost
  user: null
Kafka:
  host: localhost:9092
  partition: 0
  topicToUse: GruyterMongo
Processing:
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
  identifierRegEx: .*?<identifier>(.*?)</identifier>.*
  eventTimeRegEx: .*?<datestamp>(.*?)</datestamp>.*
  mfCompatibleBeingReplaced: .*?<marc:record.*?>
  cleanUpType: Jats

