Kafka:
  host: sb-uwf3:7078
  partition: 0
  topicToUse: ECOD
OAI:
  granularity: 	YYYY-MM-DD
  httpproxy: null
  metadataPrefix: oai_dc
  resumptionToken: null
  setName: null
  setSpec:
  stoppageTime: '2017-07-09T13:10:32Z'
  timestampUTC: '2017-07-09T11:10:26Z'
  until: null
  url: http://www.e-codices.unifr.ch/oai/oai.php
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
