Kafka:
  host: sb-uwf3:7078
  partition: 1
  topicToUse: SERVAL
OAI:
  granularity: YYYY-MM-DD
  httpproxy: null
  metadataPrefix: mods
  resumptionToken: null
  setName: null
  setSpec:
  stoppageTime: '2017-07-09T20:36:55Z'
  timestampUTC: '2017-07-11'
  until: null
  url: http://serval.unil.ch/oaiprovider
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
