Kafka:
  host: sb-uwf3:7078
  partition: 0
  topicToUse: ZORA
OAI:
  granularity: YYYY-MM-DDThh:mm:ssZ
  httpproxy: null
  metadataPrefix: oai_dc
  resumptionToken: null
  setName: null
  setSpec: 73776973736269623D596573
  stoppageTime: '2017-07-09T13:10:32Z'
  timestampUTC: '2017-07-09T11:10:26Z'
  until: null
  url: http://www.zora.uzh.ch/cgi/oai2
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
